return {
  { import = "plugins.override.nvim-lspconfig" },
  { import = "plugins.override.conform" },
  { import = "plugins.override.mason" },
  { import = "plugins.override.nvim-treesitter" },
  { import = "plugins.spec.copilot" },
  { import = "plugins.override.nvterm" },
  { import = "plugins.spec.hardtime" },
  { import = "plugins.override.indent-blankline" },
  { import = "plugins.override.nvim-cmp" },
  { import = "plugins.spec.nvim-highlight-colors" },
  { import = "plugins.spec.nvim-surround" },
  { import = "plugins.spec.nvim-ts-autotag" },
  { import = "plugins.spec.nvim-ufo" },
  { import = "plugins.spec.vim-be-good" },
  { import = "plugins.spec.screenkey" },
  { import = "plugins.spec.tiny-inline-diagnostic" },
  { import = "plugins.spec.undotree" },
  { import = "plugins.spec.oil" },
}
